#ifndef RS_ERR_CODE
#define RS_ERR_CODE

namespace rs
{
	enum ErrCode
	{
		ERR_NO = 0,
		ERR_FILE_OPEN_FAILED,
		ERR_DECODE_VIDEO = 100,
		ERR_ENCODE_VIDEO,
		ERR_CODEC_NOT_FOUND,
		ERR_COULD_NOT_OPEN_CODEC,
		ERR_COULD_NOT_ALLOCATE_VIDEO_CODEC_CONTEXT,
		ERR_COULD_NOT_ALLOCATE_VIDEO_FRAME,
		ERR_COULD_NOT_ALLOCATE_RAW_VIDEO_BUFFER,
		ERR_ENCODE_FRAME,
		ERR_UNKNOWN = 999
	};
}

#endif